### ISSUE TITLE
[BUG REPORT] It no work in Safari

### ISSUE THREAD

**Issue by Gerzer** [rpi-crisis/crisis#33]
**Environment (please complete the following information):**
 - Device: iPhone 13 Pro
 - OS: iOS 15.4
 - Safari

**Describe the bug**
It no work 😭

**Explain Steps To Reproduce**
1. Open Safari
2. Go to https://rpicrisis.org
3. Type something in the search box
4. It no work

**Expected behavior**
It work

**Comment by TrevorBrunette** [comment]
Closed by https://github.com/rpi-crisis/crisis/pull/32
